### ISSUE TITLE
Document babel 6 config

### ISSUE THREAD

**Issue by dtothefp** [deepsweet/isparta-loader#10]
would be useful to document babel 6 configs that can be passed as options to isparta-loader. My project cannot use config straight from .babelrc because some of my plugins are not yet babel 6 compatible. I was able to use the new isparta-loader though with the following config. Hopefully this save others some debugging time. Also, would be useful to merge the `options` rather than having to redefine all of them

``` js
//webpack.config
export default {
  isparta: {
    embedSource: true,
    noAutoWrap: true,
    babel: {
      presets: ['es2015', 'stage-0', 'react']
    }
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'isparta',
        exclude: [
          /(test|node_modules)/,
          addbase(srcDir, scriptDir, 'index.js') //exclude react component mounting
        ]
      }
    ]
  }
}
```

**Comment by lmk123** [comment]
OMG, you save a lot of time for me!

I use async/await functions ( stage-3 ) in Babel 6, and I try to follow README.md to generate code coverage, but I got many errors on `async function some() {  }` expression in `js` file.

Your config options figure me out: I need to add babel 6 config in webpack.config.js so isparta can parse async/await functions.

Thank you very much!

**Comment by dtothefp** [comment]
:neckbeard: thanks for the update @deepsweet
