### ISSUE TITLE
babel-loader no longer reads from webpack.babel

### ISSUE THREAD

**Issue by graingert** [deepsweet/isparta-loader#12]
it only uses loader query config.

**Comment by deepsweet** [comment]
thanks for the info.

so... I'm going to limit configuration capabilities:

``` js
webpack: {
    // WILL BE REMOVED
    // babel: {
    //    presets: ['es2015', 'stage-0', 'react']
    // },
    // *optional* isparta options: istanbul behind isparta will use it
    isparta: {
        embedSource: true,
        noAutoWrap: true,
        // these babel options will be passed only to isparta and not to babel-loader
        babel: {
            presets: ['es2015', 'stage-0', 'react']
        }
    }
}
```

because there is no longer need to reuse/share `babel` field.

any objections?

**Comment by deepsweet** [comment]
[actually it still reads](https://github.com/babel/babel-loader/blob/9575d13da9fae35220a8e12ed67b70e348236e4f/index.js#L36)

**Comment by graingert** [comment]
@deepsweet hmm it's no longer a documented feature https://github.com/babel/babel-loader/commit/57566a71a94cc27757e5a334441a98fcde802cd6

**Comment by deepsweet** [comment]
that's very strange... anyway let's wait when it will be completely removed, they will have to bump major version.
