### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by axelson** [deepsweet/isparta-loader#14]
Is this project deprecated in favor of https://github.com/deepsweet/babel-istanbul-loader?

From the README it is not clear

**Comment by deepsweet** [comment]
no, [babel-istanbul](https://github.com/jmcriffey/babel-istanbul) is just an alternative to [isparta](https://github.com/douglasduteil/isparta), so you have to decide which tool to use. I'll update README to be more clear about this, thanks.
